version: '3.8'
services:
  quota-db:
    image: mysql
    container_name: quota-db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=quota
    ports:
      - "3306:3306"
    volumes:
      - .dbdata/:/var/lib/mysql

  quota-es-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18-amd64
    container_name: quota-es-db
    environment:
      - discovery.type=single-node
      - http.port=9200
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - .es/data1:/var/lib/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - quota-development

  quota-kibana:
    image: docker.elastic.co/kibana/kibana:7.17.18
    container_name: quota-kibana
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_HOSTS=["http://quota-es-db:9200"]
    ports:
      - 5601:5601
    depends_on:
      - quota-es-db
    networks:
      - quota-development

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - quota-development

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - quota-development

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - quota-development
    depends_on:
      - kafka
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

networks:
  quota-development:
    name: quota-development